"use client";
import { useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { drawThreeCards, type DrawnCard } from "@/lib/tarot";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { toLegacyTarotResponse } from "@/lib/legacy-tarot";

export default function Home(){const [user,setUser]=useState<User|null>(null),[question,setQuestion]=useState(""),[cards,setCards]=useState<DrawnCard[]>([]),[revealed,setRevealed]=useState(0),[reading,setReading]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
useEffect(()=>{const s=getSupabaseBrowserClient();s.auth.getUser().then(({data})=>setUser(data.user));const {data:{subscription}}=s.auth.onAuthStateChange((_,session)=>setUser(session?.user??null));return()=>subscription.unsubscribe()},[]);
async function login(){const s=getSupabaseBrowserClient();await s.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin}})}
function draw(){if(!question.trim())return setError("먼저 마음속 질문을 적어 주세요.");setError("");setCards(drawThreeCards());setRevealed(0);setReading("")}
async function interpret(){setLoading(true);setError("");try{const r=await fetch("/api/reading",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,cards})});const raw=await r.text();let j:{error?:string;interpretation?:string}={};try{j=raw?JSON.parse(raw):{}}catch{throw Error("AI 서버가 올바른 응답을 반환하지 않았습니다. 잠시 뒤 다시 시도해 주세요.")}if(!r.ok)throw Error(j.error||"AI 리딩 요청에 실패했습니다.");if(!j.interpretation)throw Error("AI 풀이가 비어 있습니다.");setReading(j.interpretation);const s=getSupabaseBrowserClient();const legacyRow=toLegacyTarotResponse(question,cards,j.interpretation);const saved=await s.from("survey_responses").insert({user_id:user?.id,...legacyRow});if(saved.error)throw Error(`리딩은 생성됐지만 저장에 실패했습니다: ${saved.error.message}`)}catch(e){setError(e instanceof Error?e.message:"풀이를 불러오지 못했습니다.")}finally{setLoading(false)}}
return <main><header><b>달빛 타로</b>{user?<span>{user.email} · <a href="/admin">관리자</a></span>:<button onClick={login}>Google 로그인</button>}</header><section className="hero"><p>THREE CARD READING</p><h1>오늘, 카드에게<br/>무엇을 물어볼까요?</h1>{!user?<button onClick={login}>로그인하고 리딩 시작</button>:<><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="예: 지금 이 선택을 계속해도 될까요?"/><button onClick={draw}>카드 3장 뽑기</button></>}</section>{error&&<aside>{error}</aside>}{cards.length>0&&<section className="spread">{cards.map((c,i)=><article className={i<revealed?"card open":"card"} key={c.id} onClick={()=>setRevealed(Math.max(revealed,i+1))}>{i<revealed?<><img src={c.image} alt={c.name}/><h2>{["과거","현재","조언"][i]}</h2><strong>{c.name}</strong><small>{c.orientation==="upright"?"정방향":"역방향"}</small></>:<div>✦<br/><small>{i+1}번째 카드</small></div>}</article>)}</section>}{cards.length===3&&revealed===3&&!reading&&<div className="center"><button onClick={interpret} disabled={loading}>{loading?"별을 읽는 중…":"세 장의 이야기 듣기"}</button></div>}{reading&&<section className="reading"><p>당신을 위한 리딩</p><h2>{question}</h2><div>{reading}</div><button onClick={()=>{setCards([]);setReading("");setQuestion("")}}>새 질문 하기</button></section>}<footer>타로는 자기 성찰을 위한 상징적 도구이며, 미래를 단정하지 않습니다.</footer></main>}
