export default function HowPage() {
  return <main className="how"><header><b>달빛 타로 · 제작 노트</b><a href="/">서비스로 돌아가기</a></header><article><p className="kicker">FROM IDEA TO DEPLOYMENT</p><h1>3장의 카드가<br/>웹서비스가 되기까지</h1><p className="lead">아이디어를 정하고, 로그인·데이터베이스·AI 풀이·배포를 연결하며 실제로 겪은 문제와 해결 과정을 정리한 강의용 제작 기록입니다.</p>
  <section><h2>1. 문제 정의</h2><div className="grid"><div><strong>사용자 경험</strong><p>질문을 적고, 무작위 카드 3장을 뽑고, 각 카드의 의미를 AI가 하나의 이야기로 연결한다.</p></div><div><strong>운영 조건</strong><p>Google 로그인 사용자만 시작할 수 있고, 결과는 나중에 다시 볼 수 있도록 저장한다.</p></div><div><strong>관리자 기능</strong><p>관리자 계정은 최근 질문·카드 조합·응답 시각을 확인한다.</p></div></div></section>
  <section><h2>2. 서비스 구조</h2><pre>{`브라우저 (Next.js)
  ├─ Google 로그인 ──────────────┐
  ├─ 카드 3장 무작위 추첨          │
  └─ /api/reading ─ Gemini API     │
                                  ▼
                         Supabase (Auth + PostgreSQL)
                         tarot_readings 테이블`}</pre><p>프론트엔드는 Vercel에서 배포하고, 로그인과 데이터 저장은 Supabase가 담당합니다. AI 키는 절대 브라우저에 넣지 않고 Vercel 서버 API에서만 사용합니다.</p></section>
  <section><h2>3. 구현 순서</h2><ol><li><b>카드 데이터 만들기</b><span>메이저 아르카나 22장을 카드 이름, 키워드, 이미지로 정의하고 중복 없이 3장을 뽑는 함수를 만들었습니다.</span></li><li><b>로그인 제한</b><span>Supabase Auth의 Google OAuth를 연결해 로그인 전에는 게임 시작 버튼만 보이게 했습니다.</span></li><li><b>DB 보안</b><span><code>tarot_readings</code> 테이블과 RLS 정책을 작성해 사용자는 자기 결과만 저장·조회하고, 관리자만 전체 기록을 조회하게 했습니다.</span></li><li><b>AI 리딩 API</b><span>카드의 과거·현재·조언 역할과 질문을 Gemini 서버 API에 보내 한국어 풀이를 받습니다.</span></li><li><b>Vercel 배포</b><span>GitHub <code>main</code> 브랜치 푸시가 Vercel 배포로 이어지게 했습니다.</span></li></ol></section>
  <section><h2>4. 실제 시행착오와 해결</h2><div className="lessons"><div><b>환경 변수가 없다는 오류</b><p><em>증상</em> Supabase 환경 변수가 없다는 클라이언트 예외가 발생했습니다.</p><p><em>원인</em> Vercel 프로젝트가 여러 개여서, 실제 접속한 도메인과 변수를 넣은 프로젝트가 달랐습니다.</p><p><em>교훈</em> 배포 주소, Vercel 프로젝트 이름, Production 환경을 항상 한 세트로 확인합니다.</p></div><div><b>Google 로그인 뒤 다른 도메인으로 이동</b><p><em>증상</em> 로그인 뒤 예전 Vercel 주소로 돌아갔습니다.</p><p><em>원인</em> Supabase의 Site URL / Redirect URL이 이전 주소를 가리켰습니다.</p><p><em>교훈</em> OAuth에서는 배포 주소가 바뀔 때 Supabase Redirect URL도 반드시 갱신합니다.</p></div><div><b>OpenAI 429 quota exceeded</b><p><em>증상</em> 키는 인식됐지만 AI 풀이가 실패했습니다.</p><p><em>원인</em> ChatGPT 구독과 API 과금은 별도이며, API 프로젝트에 사용 가능 크레딧이 없었습니다.</p><p><em>교훈</em> 모델 호출 전에는 API 키·결제·월간 한도를 따로 확인합니다.</p></div><div><b>Gemini 모델 404</b><p><em>증상</em> Gemini 키를 넣은 뒤에도 모델을 찾을 수 없었습니다.</p><p><em>원인</em> 이전 모델이 신규 사용자에게 더 이상 제공되지 않았습니다.</p><p><em>교훈</em> API 오류는 키만 의심하지 말고 공식 모델 목록과 모델 사용 가능 여부를 확인합니다.</p></div><div><b>JSON 파싱 오류</b><p><em>증상</em> 서버가 빈 응답을 주자 브라우저에서 JSON 파싱 오류가 났습니다.</p><p><em>해결</em> 응답 본문을 먼저 텍스트로 읽고, JSON 여부와 오류 메시지를 안전하게 처리했습니다.</p><p><em>교훈</em> 외부 API 응답은 성공·오류·빈 응답을 모두 가정해서 작성합니다.</p></div></div></section>
  <section><h2>5. 수업에서 강조할 팁</h2><ul><li><b>“예쁘게 만들기” 다음 단계는 연결하기입니다.</b> UI, 로그인, DB, API, 배포는 서로 다른 책임을 가집니다.</li><li><b>키는 코드에 넣지 않습니다.</b> 공개 가능한 Supabase anon 키와 비공개 Gemini API 키를 구분합니다.</li><li><b>에러 메시지는 증거입니다.</b> 401은 인증, 429는 한도, 404는 주소·모델·경로 문제일 가능성이 큽니다.</li><li><b>배포는 마지막 버튼이 아닙니다.</b> Production 환경 변수, Redirect URL, 실제 도메인까지 검증해야 완료입니다.</li><li><b>테스트를 남깁니다.</b> 카드가 3장인지, 중복이 없는지 같은 핵심 규칙은 자동 테스트로 확인합니다.</li></ul></section>
  <section className="check"><h2>배포 전 체크리스트</h2><p>□ Vercel의 실제 Production 프로젝트에 환경 변수가 있는가? &nbsp; □ Supabase SQL과 RLS를 실행했는가? &nbsp; □ Google OAuth Redirect URL은 현재 도메인인가? &nbsp; □ Gemini 모델 이름과 API 한도를 확인했는가? &nbsp; □ 로그인·카드 추첨·AI 리딩·DB 저장을 실제로 한 번씩 검증했는가?</p></section></article></main>
}
